
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc3
  labels:
    app: nginx
  namespace: velero
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi 
#  storageClassName: csi-hostpath-sc