
apiVersion: v1
kind: Pod
metadata:
  name: nginx-test3
  labels:
    app: nginx
  namespace: velero
spec:
  volumes:
    - name: mystorage
      persistentVolumeClaim:
        claimName: nginx-pvc3
  containers:
    - name: task-pv-container
      image: docker.iranrepo.ir/nginx:alpine
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: mystorage