#apiVersion: v1
#kind: Namespace
#metadata:   
#  name: test-nginx
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ceph-ext
  labels:
    app: nginx
  namespace: test-velero
spec:
#  storageClassName: rook-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi 
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-test
  namespace: test-velero
spec:
  volumes:
    - name: mystorage
      persistentVolumeClaim:
        claimName: ceph-ext
  containers:
    - name: task-pv-container
      image: docker.iranrepo.ir/nginx:alpine
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: mystorage